seml:
  name: dimenetpp
  executable: 'train_seml.py'
  project_root_dir: '.'
  output_dir: '~/logs'

slurm:
  experiments_per_job: 3
  sbatch_options:
    qos: studentprio
    gres: gpu:1
    mem:  32G
    cpus-per-task: 6
    time: 30-00:00

fixed:
  model_name: "dimenet++"

  emb_size: 128
  out_emb_size: 256
  int_emb_size: 64
  basis_emb_size: 8
  num_blocks: 4

  num_radial: 12
  num_spherical: 12

  cutoff: 2.5
  num_before_skip: 1
  num_after_skip: 2
  num_dense_output: 3

  num_train: None
  num_valid: None
  data_seed: 42
  dataset: "../data/qm9"
  logdir: "logs"

  num_steps: 3000000
  ema_decay: 0.999

  learning_rate: 0.001
  warmup_steps: 3000
  decay_rate: 0.01
  decay_steps: 4000000

  batch_size: 32
  evaluation_interval: 10000
  save_interval: 10000
  restart: None
  comment: "DimeNet++"

grid:
  seed:
    type: range
    min: 0
    max: 5
    step: 1
  dist:
    type: choice
    options:
      - {type: ppr, alpha: 0.15}
      - {type: rdkit_bounds}
      - {type: ppr_rdkit_bounds, alpha: 0.15}
  ablation:
    type: choice
    options: [const_both, const_angle]

zero_init:
  fixed:
    output_init: 'zeros'
  grid:
    targets:
      type: choice
      options:
        - ['mu']
        - ['homo']
        - ['lumo']
        - ['gap']
        - ['zpve']

glorot_init:
  fixed:
    output_init: 'GlorotOrthogonal'
  grid:
    targets:
      type: choice
      options:
        - ['U0']
        - ['alpha']
        - ['r2']
        - ['U']
        - ['H']
        - ['G']
        - ['Cv']
